[tool.poetry]
name = "youtube-shorts"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
librosa = "^0.10.1"
transformers = "4.37.0"
soundfile = "^0.12.1"
evaluate = "^0.4.1"
datasets = "2.16.1"
accelerate = "^0.27.2"
jiwer = "^3.0.3"
gradio = "^4.19.2"
ffmpeg = "^1.4"
openai = "1.9.0"
rouge = "1.0.1"
nltk = "3.8.1"
torch = "1.11.0"
langchain = "0.1.3"
moviepy = "^1.0.3"
pytube = "^15.0.0"
spacy = "^3.7.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
